jump-dev/Hypatia.jl

.travis.yml
Project.toml

relax version bounds for julia and run julia nightly in travis

---

src/MathOptInterface/cones.jl
src/MathOptInterface/wrapper.jl
test/moi.jl
test/runmoitests.jl

will uncomment new test when https://github.com/jump-dev/MathOptInterface.jl/pull/1175 is merged

test more real types thru MOI tests

---

examples/runbenchmarks.jl
examples/spawn.jl

only modifies benchmark script, which is not tested in CI

make benchmark script work on julia 1.5

---

src/Cones/Cones.jl
src/Cones/doublynonnegativetri.jl
src/Cones/epinormeucl.jl
src/Cones/epinorminf.jl
src/Cones/epinormspectral.jl
src/Cones/epipersquare.jl
src/Cones/episumperentropy.jl
src/Cones/hypogeomean.jl
src/Cones/hypoperlog.jl
src/Cones/hypoperlogdettri.jl
src/Cones/hypopowermean.jl
src/Cones/hyporootdettri.jl
src/Cones/linmatrixineq.jl
src/Cones/matrixepipersquare.jl
src/Cones/nonnegative.jl
src/Cones/possemideftri.jl
src/Cones/possemideftrisparse.jl
src/Cones/power.jl
src/Cones/wsosinterpepinormeucl.jl
src/Cones/wsosinterpepinormone.jl
src/Cones/wsosinterpnonnegative.jl
src/Cones/wsosinterppossemideftri.jl
src/Solvers/Solvers.jl
src/Solvers/linesearch.jl
src/Solvers/process.jl
src/Solvers/steppers/heurcomb.jl

there was a bug in the initial point finding, though it did not seem to affect the number of iterations by more than a few in all cases

minor bug fixes and cleanup

---

examples/runbenchmarks.jl
examples/spawn.jl

only modifies benchmark script

fix some benchmark script failures

---

examples/processbenchmarks.jl

allow getting nu in postprocessing

---

src/ModelUtilities/interpolate.jl

this was causing compilation errors during tests on Julia 1.7 master

fix type issues with interpolation functions

---

src/MathOptInterface/wrapper.jl

correct MOI.Silent

---

src/Solvers/Solvers.jl
src/Solvers/steppers/combined.jl
src/Solvers/steppers/predorcent.jl

currently not printed, but this could be an option for verbosity. 
useful for benchmarking

add timings for subprocedures

---

src/Cones/wsosinterpnonnegative.jl

this is L^2*U instead of L*U^2

faster TOA for wsos nonnegative

---

src/Cones/linmatrixineq.jl

get a better LMI TOA

---

src/Cones/Cones.jl
src/Cones/doublynonnegativetri.jl
src/Cones/epinormeucl.jl
src/Cones/epinorminf.jl
src/Cones/epinormspectral.jl
src/Cones/epiperentropy.jl
src/Cones/epipersquare.jl
src/Cones/epipertraceentropytri.jl
src/Cones/epirelentropy.jl
src/Cones/epitracerelentropytri.jl
src/Cones/generalizedpower.jl
src/Cones/hypogeomean.jl
src/Cones/hypoperlog.jl
src/Cones/hypoperlogdettri.jl
src/Cones/hypopowermean.jl
src/Cones/hyporootdettri.jl
src/Cones/linmatrixineq.jl
src/Cones/matrixepipersquare.jl
src/Cones/nonnegative.jl
src/Cones/possemideftri.jl
src/Cones/possemideftrisparse.jl
src/Cones/wsosinterpepinormeucl.jl
src/Cones/wsosinterpepinormone.jl
src/Cones/wsosinterpnonnegative.jl
src/Cones/wsosinterppossemideftri.jl
src/Solvers/steppers/common.jl
src/Solvers/systemsolvers/common.jl
src/Solvers/systemsolvers/qrchol.jl
test/cone.jl

use expensive hessian products only when needed

---

benchmarks/stepper/run.jl
examples/densityest/native_test.jl
examples/doptimaldesign/native_test.jl
examples/envelope/native_test.jl
examples/matrixregression/native_test.jl
examples/polymin/native_test.jl
examples/portfolio/native_test.jl

removes the need to comment/uncomment some lines in run.jl

make minor changes to run benchmarks

---

examples/Examples.jl

the dict storing examples data had no instances

fix data not being added into ordereddict

---

benchmarks/natvsext/analyze.jl
benchmarks/natvsext/run.jl
examples/doptimaldesign/JuMP_benchmark.jl
examples/matrixcompletion/JuMP_benchmark.jl

update scripts to run all extenders

---

src/MathOptInterface/wrapper.jl

see https://github.com/jump-dev/MathOptInterface.jl/pull/1534

remove warn_attributes option

---

src/Cones/arrayutilities.jl
src/Cones/epinormspectral.jl
src/Cones/matrixepipersquare.jl

simpler, more-efficient oracles and better numerics. and finally an inverse hessian product. feas checks can still be sped up but I will leave that for a future PR

reimplement spectral norm cone using SVD-based oracles

---

src/Solvers/Solvers.jl
src/Solvers/process.jl

add tolerance option for primal or dual inconsistent equalities status

---

Project.toml
examples/classicalquantum/JuMP.jl

update MOI to 1, fix error in classicalquantum example

---

src/linearalgebra/Pardiso.jl

I don't have Pardiso so I didn't test. But I assume that this fixes #816.

Fix types in Pardiso.jl

---

README.md
examples/JuMP_utils.jl
src/MathOptInterface/transform.jl
src/MathOptInterface/wrapper.jl

Addresses #823, I think. 
The test should really come from MOI.Test.

reorder rescaling and permuting for h

---

src/linearalgebra/Pardiso.jl

...as the parameter was removed in #825

Remove parametric type from constructor
